import React from 'react';

import styles from '../styles/Home.module.css';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<div className={styles.root}>
					<h1>Nextjs Demo</h1>
					<div className={styles.content}>{children}</div>
				</div>
			</body>
		</html>
	);
}
